### ISSUE TITLE
Allow DateStyle to be "ISO, MDY", "ISO, DMY", or "ISO, YMD".

### ISSUE THREAD

**Issue by AMBIENTE1** [codewinsdotcom/PostgresClientKit#30]
Hallo, I would like to change parameter datestyle from ISO, MDY to ISO, DMY in Parameter.swift
When I try:
let text = "SET DateStyle TO 'ISO, DMY';"
let cursor = try Database.connection().prepareStatement(text: text).execute()

error: Invalid value for Postgres parameter (response.name): ISO, DMY (must be ISO, MDY); closing connection

Please what is the best way to do this?

**Comment by pitfield** [comment]
PostgresClientKit sets the Postgres `DATESTYLE` parameter to `ISO, MDY` and doesn't allow this value to be changed.  This prevents misinterpretation of dates sent over the wire due to configuration mismatches.

If you want to control the format of dates in your user interface, you should use the `PostgresDate` type (or `PostgresTimestampWithTimeZone` for date/time values) and a `DateFormatter` (from the Foundation framework).

**Comment by AMBIENTE1** [comment]
In my Postgres database are many funcs, where the date is set as string in format DD.MM.YYYY. ISO DMY is required.  Would it be possible to set ISO DMY or MDY as a parameter please?

**Comment by pitfield** [comment]
Could please try this commit (tip of the develop branch)?  40fe0ffa62a4d3c9b2c0c2ba2f3bc50cda6febf2

This should allow you to set the `DATESTYLE` paraameter to `ISO, MDY`, `ISO, DMY`, or `ISO, YMD`.

**Comment by AMBIENTE1** [comment]
If i used playground, i couldn't use import PostgresClientKit :No such module 'PostgresClientKit'

But i modified the test and it worked properly.
Can you please add this modification to the release?

**Comment by pitfield** [comment]
Released in v1.3.1.

**Comment by AMBIENTE1** [comment]
thank you so much
